name: pybpmn
dependencies:
  - python>=3.8
  - ipython
  - pip
  - ipykernel
  - nbformat # for %run in jupyter
  - click # scripts
  - pip:
      - -e .  # install git checkout of pybpmn in editable mode
  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
      - pre_commit
      - tox
